this is the latest one :-)))
Integrify-Team-4/Tindev pull request #100
Opened 2021-01-15 14:29 UTC by dilippoudel

2021-01-15 18:41 UTC, Wyfy0107 requested changes

2021-01-15 18:41 UTC, Wyfy0107 commented on src/controllers/uploader.ts
> +    console.log('the user is ', req.user)
🐞

2021-01-15 18:41 UTC, Wyfy0107 commented on src/controllers/uploader.ts
> +    console.log(req.body, '%%%%%%%%%%%')
🐛

2021-01-15 18:41 UTC, Wyfy0107 commented on src/routers/uploadProfile.ts
> +import tokenVerify from '../middlewares/tokenVerify'
Use this in the router

2021-01-19 11:52 UTC, Wyfy0107 approved these changes
💯

2021-01-19 12:23 UTC, dilippoudel commented
can i merge it now?

2021-01-20 09:05 UTC, merged